all: simple_gamble.pdf change_in_utility.pdf

remake: clear_all all

simple_gamble.pdf:
	/usr/bin/python3 simple_gamble.py

change_in_utility.pdf:
	/usr/bin/python3 change_in_utility.py

clear_all: 
	rm *.pdf
	rm *.png


